import { useState } from "react";
import { Download, Plus, Search } from "lucide-react";
import { groupRequests, usageTotal } from "./observability";
import { simulateRequest } from "./domain";

const stamp = value => value?.slice(0,16).replace("T"," ") || "—";
const uid = prefix => `${prefix}-${Date.now()}`;
const title = { goods:"商品与套餐",prices:"价格管理",orders:"订单与订阅",listing:"上架与展示",announcements:"公告与服务通知",metering:"计量明细",ledger:"账户与额度流水",bills:"客户账单",settlement:"服务商对账与结算",adjustments:"退款与调账",artifacts:"模型制品与镜像","request-security":"请求安全策略","data-policy":"数据使用策略",abuse:"访问与滥用防护","security-events":"安全事件",admins:"后台人员与角色",audit:"操作审计",approvals:"审批与变更规则",integrations:"通知与集成",settings:"基础配置","customer-analysis":"客户分析","model-analysis":"模型分析","supply-analysis":"供给分析","profit-analysis":"收入与成本" };
const configs = {
  goods:{collection:"products",cols:[["code","商品编码"],["name","商品名称"],["billingMode","计费方式"],["price","基础价格"],["status","状态"]],fields:[["code","商品编码"],["name","商品名称"],["billingMode","计费方式"],["price","基础价格","number"]]},
  prices:{collection:"prices",cols:[["id","价格版本"],["item","计费项"],["unit","单位"],["amount","单价"],["effectiveAt","生效时间"],["status","状态"]],fields:[["item","计费项"],["unit","单位"],["amount","单价","number"],["effectiveAt","生效时间","date"]]},
  announcements:{collection:"announcements",cols:[["title","标题"],["audience","受众"],["channel","渠道"],["effectiveAt","生效时间"],["status","状态"]],fields:[["title","标题"],["audience","受众"],["channel","渠道"],["effectiveAt","生效时间","date"]]},
  admins:{collection:"admins",cols:[["account","账号"],["name","姓名"],["role","角色"],["scope","数据范围"],["status","状态"]],fields:[["account","账号"],["name","姓名"],["role","角色"],["scope","数据范围"]]},
  approvals:{collection:"approvals",cols:[["name","规则名称"],["condition","命中条件"],["approverRole","审批角色"],["status","状态"]],fields:[["name","规则名称"],["condition","命中条件"],["approverRole","审批角色"]]},
  integrations:{collection:"integrations",cols:[["name","渠道名称"],["type","类型"],["target","模拟目标"],["events","订阅事件"],["lastResult","最近结果"],["status","状态"]],fields:[["name","渠道名称"],["type","渠道类型"],["target","模拟目标"],["events","订阅事件"]]},
};
function Head({pageId,action}) { return <div className="v2-page-head"><div><span>运营运维后台 / 专属功能</span><h1>{title[pageId]}</h1><p>数据、状态和操作在同一演示状态中联动，所有外部动作均为模拟。</p></div>{action}</div>; }
function Badge({children}) { return <em className={`v2-status ${String(children).match(/待|停|失败|未/) ? "warn":""}`}>{children}</em>; }
function Managed({pageId,state,dispatch}) {
  const cfg=configs[pageId],[query,setQuery]=useState(""),[editing,setEditing]=useState(false),[error,setError]=useState("");
  const rows=state[cfg.collection].filter(x=>Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase()));
  const save=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));for(const f of cfg.fields.filter(x=>x[2]==="number")){values[f[0]]=Number(values[f[0]]);if(values[f[0]]<0)return setError(`${f[1]}不能为负数`);}if(cfg.fields.some(f=>!values[f[0]]))return setError("请填写全部必填项");dispatch({type:"add",collection:cfg.collection,record:{id:uid(cfg.collection),...values,status:pageId==="announcements"?"草稿":"已启用"}});setEditing(false)};
  const toggle=row=>dispatch({type:"update",collection:cfg.collection,id:row.id,changes:{status:["已启用","已上架","生效中"].includes(row.status)?"停用":"已启用"}});
  return <div className="v2-page"><Head pageId={pageId} action={cfg.fields&&<button className="v2-primary" onClick={()=>setEditing(true)}><Plus/> 新建</button>}/><section className="v2-list"><div className="v2-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`搜索${title[pageId]}`}/></label></div><div className="v2-table"><table><thead><tr>{cfg.cols.map(c=><th key={c[0]}>{c[1]}</th>)}<th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{cfg.cols.map(c=><td key={c[0]}>{c[0]==="status"?<Badge>{row[c[0]]}</Badge>:Array.isArray(row[c[0]])?row[c[0]].length:row[c[0]]}</td>)}<td><button onClick={()=>toggle(row)}>{row.status==="停用"?"启用":"变更状态"}</button>{pageId==="integrations"&&<><button onClick={()=>dispatch({type:"update",collection:cfg.collection,id:row.id,changes:{lastResult:"模拟失败：连接超时"}})}>模拟失败</button>{row.lastResult?.includes("失败")&&<button onClick={()=>dispatch({type:"update",collection:cfg.collection,id:row.id,changes:{lastResult:"重试成功"}})}>重试</button>}</>}</td></tr>)}</tbody></table></div><footer>共 {rows.length} 条</footer></section>{editing&&<div className="v2-mask" onClick={()=>setEditing(false)}><aside className="entity-drawer" onClick={e=>e.stopPropagation()}><header><h2>新建{title[pageId]}</h2></header><form onSubmit={save}>{cfg.fields.map(f=><label key={f[0]}>{f[1]}<input name={f[0]} type={f[2]||"text"}/></label>)}{error&&<p className="form-error">{error}</p>}<footer><button type="button" onClick={()=>setEditing(false)}>取消</button><button className="v2-primary">保存</button></footer></form></aside></div>}</div>;
}
function Orders({state,dispatch}) { const create=()=>{const product=state.products[1]||state.products[0],tenant=state.tenants[0],stamp=Date.now();dispatch({type:"add",collection:"orders",record:{id:`order-${stamp}`,orderNo:`ORD-${stamp}`,tenantId:tenant.id,productId:product.id,amount:product.price,entitlement:100000000,status:"待开通",timeline:["订单创建"]}})};const activate=x=>{if(x.status!=="待开通"||state.ledger.some(row=>row.sourceId===`entitlement:${x.id}`))return;dispatch({type:"batch",objectId:x.orderNo,changes:[{type:"update",collection:"orders",id:x.id,changes:{status:"已开通",timeline:[...x.timeline,"支付成功","权益发放"]}},{type:"add",collection:"ledger",record:{id:uid("ledger"),accountId:x.tenantId,sourceId:`entitlement:${x.id}`,type:"订购权益",delta:x.entitlement,balance:x.entitlement,reason:x.orderNo,status:"已完成"}}]})};const cancel=x=>dispatch({type:"update",collection:"orders",id:x.id,changes:{status:"已退订",timeline:[...x.timeline,"用户退订"]}});return <div className="v2-page"><Head pageId="orders" action={<button className="v2-primary" onClick={create}><Plus/> 创建演示订单</button>}/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>订单号</th><th>租户</th><th>商品</th><th>金额</th><th>权益</th><th>状态</th><th>时间线</th><th>操作</th></tr></thead><tbody>{state.orders.map(x=><tr key={x.id}><td>{x.orderNo}</td><td>{state.tenants.find(t=>t.id===x.tenantId)?.name}</td><td>{state.products.find(p=>p.id===x.productId)?.name}</td><td>¥{x.amount}</td><td>{x.entitlement.toLocaleString()}</td><td><Badge>{x.status}</Badge></td><td>{x.timeline.join(" → ")}</td><td>{x.status==="待开通"&&<button onClick={()=>activate(x)}>模拟开通</button>}{["已开通","生效中"].includes(x.status)&&<button onClick={()=>cancel(x)}>退订</button>}</td></tr>)}</tbody></table></div></section></div> }
function Metering({state,dispatch}) { const [keyId,setKeyId]=useState(state.apiKeys.find(x=>x.status==="有效")?.id||""),[modelId,setModelId]=useState(state.models[0]?.id||""),[result,setResult]=useState(""); const run=()=>{const requestId=`req_demo_${Date.now()}`,planned=simulateRequest(state,{requestId,keyId,modelId});dispatch({type:"batch",objectId:requestId,changes:planned.changes});setResult(`${planned.request.httpStatus} · ${planned.request.requestId} · ${planned.request.attempts.at(-1).error||"已计量扣减"}`)}; return <div className="v2-page"><Head pageId="metering"/><section className="request-simulator"><div><b>模拟调用</b><span>{result||"选择 Key ID 与 Model ID，验证鉴权、额度、限流、路由和计量"}</span></div><select value={keyId} onChange={e=>setKeyId(e.target.value)}>{state.apiKeys.map(x=><option value={x.id} key={x.id}>{x.keyId}</option>)}</select><select value={modelId} onChange={e=>setModelId(e.target.value)}>{state.models.map(x=><option value={x.id} key={x.id}>{x.modelId}</option>)}</select><button className="v2-primary" onClick={run}>发送模拟请求</button></section><section className="v2-list"><div className="v2-table"><table><thead><tr><th>Request ID</th><th>客户</th><th>Model ID</th><th>计量项</th><th>数量</th><th>价格快照</th><th>金额</th><th>状态</th></tr></thead><tbody>{state.requests.slice(0,40).map(x=>{const qty=usageTotal(x.usage);return <tr key={x.id}><td>{x.requestId}</td><td>{state.tenants.find(t=>t.id===x.tenantId)?.name}</td><td>{state.models.find(m=>m.id===x.modelId)?.modelId}</td><td>{Object.keys(x.usage).join(" / ")}</td><td>{qty.toLocaleString()}</td><td>2026-09 生效价</td><td>¥{x.httpStatus===200?(qty/1e6*1.8).toFixed(4):"0.0000"}</td><td><Badge>{x.httpStatus===200?"已计量":"不计费"}</Badge></td></tr>})}</tbody></table></div></section></div> }
function Ledger({state}) { return <div className="v2-page"><Head pageId="ledger"/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>流水 ID</th><th>账户</th><th>来源</th><th>类型</th><th>变动</th><th>余额</th><th>原因</th><th>状态</th></tr></thead><tbody>{state.ledger.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.accountId}</td><td>{x.sourceId}</td><td>{x.type}</td><td>{x.delta.toLocaleString()}</td><td>{x.balance.toLocaleString()}</td><td>{x.reason}</td><td><Badge>{x.status}</Badge></td></tr>)}</tbody></table></div></section></div> }
function Bills({state,dispatch}) { const generate=()=>{const period="2026-09",existing=new Set(state.bills.map(x=>`${x.tenantId}:${x.period}`)),changes=state.tenants.filter(t=>!existing.has(`${t.id}:${period}`)).map(t=>{const amount=state.requests.filter(r=>r.tenantId===t.id&&r.httpStatus===200).reduce((sum,r)=>sum+usageTotal(r.usage)/1e6*1.8,0);return {type:"add",collection:"bills",record:{id:uid("bill"),billNo:`BILL-${period.replace("-","")}-${t.id}`,tenantId:t.id,period,amount:Number(amount.toFixed(2)),discount:0,paid:0,status:"待出账"}}});if(changes.length)dispatch({type:"batch",objectId:`bills:${period}`,changes})};return <div className="v2-page"><Head pageId="bills" action={<button className="v2-primary" onClick={generate}>生成 2026-09 账单</button>}/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>账单号</th><th>租户</th><th>账期</th><th>应收</th><th>优惠</th><th>实收</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.bills.map(x=><tr key={x.id}><td>{x.billNo}</td><td>{state.tenants.find(t=>t.id===x.tenantId)?.name}</td><td>{x.period}</td><td>¥{x.amount}</td><td>¥{x.discount}</td><td>¥{x.paid}</td><td><Badge>{x.status}</Badge></td><td>{x.status==="待出账"&&<button onClick={()=>dispatch({type:"update",collection:"bills",id:x.id,changes:{status:"已出账"}})}>确认出账</button>}</td></tr>)}</tbody></table></div></section></div>}
function Settlements({state,dispatch}) { const [message,setMessage]=useState(""); const preview=()=>setMessage("导入预览：12 行匹配，1 行金额差异 ¥2.50，0 行格式错误");return <div className="v2-page"><Head pageId="settlement" action={<button onClick={preview}><Download/> 导入对账预览</button>}/>{message&&<div className="v2-system-alert">{message}</div>}<section className="v2-list"><div className="v2-table"><table><thead><tr><th>结算单</th><th>服务商</th><th>账期</th><th>平台金额</th><th>服务商金额</th><th>差异</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.settlements.map(x=><tr key={x.id}><td>{x.settlementNo}</td><td>{state.providers.find(p=>p.id===x.providerId)?.name}</td><td>{x.period}</td><td>¥{x.platformAmount}</td><td>¥{x.providerAmount}</td><td>¥{x.difference}</td><td><Badge>{x.status}</Badge></td><td><button disabled={!message||x.difference!==0} onClick={()=>dispatch({type:"update",collection:"settlements",id:x.id,changes:{status:"已确认"}})}>确认结算</button>{x.difference!==0&&<button onClick={()=>dispatch({type:"update",collection:"settlements",id:x.id,changes:{difference:0,status:"差异已处理"}})}>处理差异</button>}</td></tr>)}</tbody></table></div></section></div>}
function Adjustments({state,dispatch}) { const decide=(x,approved)=>{const reason=prompt(approved?"请输入通过意见":"请输入驳回原因");if(!reason)return;const bill=state.bills.find(b=>b.id===x.billId);if(approved&&Math.abs(x.amount)>bill.amount)return alert("调账金额不能超过账单应收");const changes=[{type:"update",collection:"adjustments",id:x.id,changes:{status:approved?"已执行":"已拒绝",approvalReason:reason}}];if(approved&&!state.ledger.some(l=>l.sourceId===`adjustment:${x.id}`))changes.push({type:"add",collection:"ledger",record:{id:uid("ledger"),accountId:bill.tenantId,sourceId:`adjustment:${x.id}`,type:"账单冲正",delta:-x.amount,balance:0,reason,status:"已完成"}});dispatch({type:"batch",objectId:x.adjustmentNo,changes})};return <div className="v2-page"><Head pageId="adjustments"/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>申请号</th><th>账单</th><th>金额</th><th>原因</th><th>审批意见</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.adjustments.map(x=><tr key={x.id}><td>{x.adjustmentNo}</td><td>{state.bills.find(b=>b.id===x.billId)?.billNo}</td><td>¥{x.amount}</td><td>{x.reason}</td><td>{x.approvalReason||"—"}</td><td><Badge>{x.status}</Badge></td><td>{x.status==="待审批"&&<><button onClick={()=>decide(x,true)}>通过并执行</button><button onClick={()=>decide(x,false)}>驳回</button></>}</td></tr>)}</tbody></table></div></section></div>}
function Listing({state,dispatch}) {return <div className="v2-page"><Head pageId="listing"/><div className="listing-grid">{state.products.map((x,i)=><article key={x.id}><small>展示位 {i+1}</small><h2>{x.name}</h2><p>{x.billingMode} · 覆盖 {x.modelIds.length} 个模型</p><Badge>{x.status}</Badge><button onClick={()=>dispatch({type:"update",collection:"products",id:x.id,changes:{status:x.status==="已上架"?"已下架":"已上架"}})}>{x.status==="已上架"?"下架":"发布"}</button></article>)}</div></div>}
function Security({pageId,state,dispatch}) {const category=pageId==="request-security"?"请求内容":pageId==="data-policy"?"数据策略":"访问防护",rows=state.securityPolicies.filter(x=>x.category===category);return <div className="v2-page"><Head pageId={pageId}/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>策略</th><th>作用范围</th><th>动作</th><th>命中</th><th>状态</th><th>测试 / 操作</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.scope}</td><td>{x.action}</td><td>{x.hits}</td><td><Badge>{x.status}</Badge></td><td><button onClick={()=>dispatch({type:"update",collection:"securityPolicies",id:x.id,changes:{hits:x.hits+1}})}>模拟命中</button><button onClick={()=>dispatch({type:"update",collection:"securityPolicies",id:x.id,changes:{status:x.status==="已启用"?"停用":"已启用"}})}>启停</button></td></tr>)}</tbody></table></div></section></div>}
function SecurityEvents({state,dispatch}) {return <div className="v2-page"><Head pageId="security-events"/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>事件</th><th>策略</th><th>Request ID</th><th>Key ID</th><th>等级</th><th>负责人</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.securityEvents.map(x=><tr key={x.id}><td>{x.eventNo}</td><td>{state.securityPolicies.find(p=>p.id===x.policyId)?.name}</td><td>{x.requestId}</td><td>{state.apiKeys.find(k=>k.id===x.keyId)?.keyId}</td><td><Badge>{x.severity}</Badge></td><td>{x.assignee}</td><td><Badge>{x.status}</Badge></td><td><button onClick={()=>dispatch({type:"update",collection:"securityEvents",id:x.id,changes:{status:"已处置",conclusion:"演示处置完成"}})}>处置</button></td></tr>)}</tbody></table></div></section></div>}
function ApprovalCenter({state,dispatch}) {const decide=(x,approved)=>{const reason=prompt(approved?"请输入审批意见":"请输入驳回原因");if(!reason)return;const bill=state.bills.find(b=>b.id===x.billId),changes=[{type:"update",collection:"adjustments",id:x.id,changes:{status:approved?"已执行":"已拒绝",approvalReason:reason}}];if(approved&&!state.ledger.some(l=>l.sourceId===`adjustment:${x.id}`))changes.push({type:"add",collection:"ledger",record:{id:uid("ledger"),accountId:bill.tenantId,sourceId:`adjustment:${x.id}`,type:"账单冲正",delta:-x.amount,balance:0,reason,status:"已完成"}});dispatch({type:"batch",objectId:x.adjustmentNo,changes})};return <div className="v2-page"><Head pageId="approvals"/><section className="v2-summary"><article><span>待审批</span><b>{state.adjustments.filter(x=>x.status==="待审批").length}</b><small>调账与高风险变更</small></article><article><span>启用规则</span><b>{state.approvals.filter(x=>x.status==="已启用").length}</b><small>按角色自动分派</small></article></section><section className="v2-list"><div className="v2-table"><table><thead><tr><th>申请号</th><th>类型</th><th>金额</th><th>申请原因</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.adjustments.map(x=><tr key={x.id}><td>{x.adjustmentNo}</td><td>账单调账</td><td>¥{x.amount}</td><td>{x.reason}</td><td><Badge>{x.status}</Badge></td><td>{x.status==="待审批"&&<><button onClick={()=>decide(x,true)}>通过</button><button onClick={()=>decide(x,false)}>驳回</button></>}</td></tr>)}</tbody></table></div></section></div>}
function Audit({state}) {return <div className="v2-page"><Head pageId="audit"/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>审计 ID</th><th>操作人</th><th>动作</th><th>对象</th><th>结果</th><th>时间</th></tr></thead><tbody>{state.audits.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.actor}</td><td>{x.action}</td><td>{x.objectId}</td><td><Badge>{x.result}</Badge></td><td>{stamp(x.createdAt)}</td></tr>)}</tbody></table></div></section></div>}
function Settings({state,dispatch}) {const save=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));dispatch({type:"setSettings",objectId:"settings",changes:{...v,retentionDays:Number(v.retentionDays),defaultTpm:Number(v.defaultTpm)}});};return <div className="v2-page"><Head pageId="settings"/><section className="settings-panel"><form onSubmit={save}><h2>平台基础参数</h2><label>环境名称<input name="environmentLabel" defaultValue={state.settings.environmentLabel}/></label><label>时区<select name="timezone" defaultValue={state.settings.timezone}><option>Asia/Shanghai</option><option>UTC</option></select></label><label>日志留存天数<input name="retentionDays" type="number" min="1" defaultValue={state.settings.retentionDays}/></label><label>默认 TPM<input name="defaultTpm" type="number" min="1" defaultValue={state.settings.defaultTpm}/></label><button className="v2-primary">保存配置</button></form></section></div>}
function Analysis({pageId,state}) {const groups=groupRequests(state.requests,pageId==="customer-analysis"?"tenantId":pageId==="supply-analysis"?"endpointId":"modelId").map(g=>({id:g.key,calls:g.requests.length,tokens:g.requests.reduce((s,x)=>s+usageTotal(x.usage),0),fail:g.requests.filter(x=>x.httpStatus>=400).length})).sort((a,b)=>b.tokens-a.tokens);return <div className="v2-page"><Head pageId={pageId}/><section className="v2-summary"><article><span>请求量</span><b>{state.requests.length}</b><small>近 14 天样本</small></article><article><span>Token / 任务量</span><b>{groups.reduce((s,x)=>s+x.tokens,0).toLocaleString()}</b><small>统一模拟口径</small></article><article><span>预估收入</span><b>¥{(groups.reduce((s,x)=>s+x.tokens,0)/1e6*1.8).toFixed(2)}</b><small>按当前价格快照</small></article></section><section className="v2-list"><div className="v2-table"><table><thead><tr><th>分析对象</th><th>请求数</th><th>用量</th><th>失败数</th><th>失败率</th><th>预估收入</th></tr></thead><tbody>{groups.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.calls}</td><td>{x.tokens.toLocaleString()}</td><td>{x.fail}</td><td>{(x.fail/x.calls*100).toFixed(2)}%</td><td>¥{(x.tokens/1e6*1.8).toFixed(2)}</td></tr>)}</tbody></table></div></section></div>}
function Artifacts({state,dispatch}){const [tab,setTab]=useState("模型制品"),rows=state.artifacts.filter(x=>x.type===tab);const add=()=>dispatch({type:"add",collection:"artifacts",record:{id:uid("artifact"),name:`${tab} ${state.artifacts.length+1}`,type:tab,version:"v1.0",digest:`sha256:${Date.now().toString(16)}`,size:"1.2 GB",validation:"待验证",status:"不可运行"}});const remove=x=>{const refs=state.deployments.filter(d=>d.artifactId===x.id);if(refs.length)return alert(`该制品被 ${refs.length} 个部署引用，不能删除`);dispatch({type:"update",collection:"artifacts",id:x.id,changes:{status:"已删除"}})};return <div className="v2-page"><Head pageId="artifacts" action={<button className="v2-primary" onClick={add}><Plus/> 登记制品</button>}/><div className="artifact-tabs">{["模型制品","基础镜像","运行时镜像"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><section className="v2-list"><div className="v2-table"><table><thead><tr><th>名称</th><th>版本</th><th>摘要</th><th>大小</th><th>引用部署</th><th>验证</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(x=>{const refs=state.deployments.filter(d=>d.artifactId===x.id).length;return <tr key={x.id}><td>{x.name}</td><td>{x.version}</td><td><code>{x.digest}</code></td><td>{x.size}</td><td>{refs}</td><td><Badge>{x.validation}</Badge></td><td><Badge>{x.status}</Badge></td><td>{x.validation!=="通过"&&<button onClick={()=>dispatch({type:"update",collection:"artifacts",id:x.id,changes:{validation:"通过",status:"可运行"}})}>模拟校验</button>}<button onClick={()=>remove(x)}>删除</button></td></tr>})}</tbody></table></div></section></div>}

export default function BusinessOperationsPage({pageId,state,dispatch}) {
  if(pageId==="approvals") return <ApprovalCenter state={state} dispatch={dispatch}/>;
  if(configs[pageId]) return <Managed pageId={pageId} state={state} dispatch={dispatch}/>;
  if(pageId==="orders") return <Orders state={state} dispatch={dispatch}/>;
  if(pageId==="metering") return <Metering state={state} dispatch={dispatch}/>;
  if(pageId==="ledger") return <Ledger state={state}/>;
  if(pageId==="bills") return <Bills state={state} dispatch={dispatch}/>;
  if(pageId==="settlement") return <Settlements state={state} dispatch={dispatch}/>;
  if(pageId==="adjustments") return <Adjustments state={state} dispatch={dispatch}/>;
  if(pageId==="listing") return <Listing state={state} dispatch={dispatch}/>;
  if(["request-security","data-policy","abuse"].includes(pageId)) return <Security pageId={pageId} state={state} dispatch={dispatch}/>;
  if(pageId==="security-events") return <SecurityEvents state={state} dispatch={dispatch}/>;
  if(pageId==="audit") return <Audit state={state}/>;
  if(pageId==="settings") return <Settings state={state} dispatch={dispatch}/>;
  if(pageId==="artifacts") return <Artifacts state={state} dispatch={dispatch}/>;
  return <Analysis pageId={pageId} state={state}/>;
}
