import { useState } from "react";
import { GitBranch, Gauge, Layers, Rocket, Shield, X } from "lucide-react";
import { simulateRequest } from "./domain";

const uid = prefix => `${prefix}-${Date.now()}`;
const meta = { routes: ["路由策略", "配置模型到端点的加权或优先级选路。", GitBranch], limits: ["限流与并发", "按租户、项目、Key、模型或端点设置有效上限。", Gauge], fallback: ["熔断与回退", "配置超时、错误率阈值和无环回退链。", Shield], cache: ["缓存策略", "按权限上下文控制缓存、TTL 和命中统计。", Layers], releases: ["配置版本与发布", "校验配置差异，发布或生成可追溯的回滚版本。", Rocket] };
const collection = { routes: "routes", limits: "limits", fallback: "fallbacks", cache: "caches", releases: "releases" };
function Header({ pageId, onNew }) { const [title, desc, Icon] = meta[pageId]; return <div className="v2-page-head inference-head"><div><span>服务运维 / 网关路由</span><h1><Icon/>{title}</h1><p>{desc}</p></div>{pageId !== "releases" && <button className="v2-primary" onClick={onNew}>＋ 新建</button>}</div>; }
function State({ value }) { return <em className={`v2-status ${["草稿", "校验失败", "已停用"].includes(value) ? "warn" : ""}`}>{value}</em>; }

function Editor({ pageId, state, dispatch, close }) {
  const [error, setError] = useState("");
  const save = event => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)), id = uid(pageId); let record;
    if (pageId === "routes") { const weightA = Number(v.weightA), weightB = Number(v.weightB), targets = [v.endpointA, v.endpointB].map(endpointId => state.endpoints.find(item => item.id === endpointId)); if (!v.routeId || weightA + weightB !== 100) return setError("Route ID 必填，两个端点权重之和必须为 100%"); if (v.endpointA === v.endpointB) return setError("两个路由端点不能重复"); if (targets.some(endpoint => !endpoint?.modelIds.includes(v.modelId))) return setError("路由端点必须映射所选 Model ID"); record = { id, routeId: v.routeId, name: v.name, modelId: v.modelId, targets: [{ endpointId: v.endpointA, weight: weightA }, { endpointId: v.endpointB, weight: weightB }], mode: "加权", status: "草稿", releaseId: null }; }
    if (pageId === "limits") { if ([v.rpm, v.tpm, v.concurrency].some(value => Number(value) < 1)) return setError("RPM、TPM 和并发必须为正整数"); record = { id, name: v.name, scopeType: v.scopeType, scopeId: v.scopeId, rpm: Number(v.rpm), tpm: Number(v.tpm), concurrency: Number(v.concurrency), status: "已启用" }; }
    if (pageId === "fallback") { if (v.primary === v.secondary) return setError("回退端点不能与主端点相同"); record = { id, name: v.name, routeId: v.routeId, timeoutMs: Number(v.timeoutMs), errorRate: Number(v.errorRate), chain: [v.primary, v.secondary], status: "已启用" }; }
    if (pageId === "cache") record = { id, name: v.name, scope: v.scope, ttl: Number(v.ttl), exclusions: v.exclusions, hitRate: 0, savedTokens: 0, status: "已启用" };
    dispatch({ type: "add", collection: collection[pageId], record }); close();
  };
  const endpointOptions = state.endpoints.map(item => <option key={item.id} value={item.id}>{item.endpointId}</option>);
  return <div className="v2-mask" onClick={close}><aside className="entity-drawer" onClick={event => event.stopPropagation()}><header><h2>新建{meta[pageId][0]}</h2><button onClick={close}><X/></button></header><form onSubmit={save}>{pageId === "routes" && <><label>Route ID<input name="routeId"/></label><label>名称<input name="name"/></label><label>Model ID<select name="modelId">{state.models.map(item => <option key={item.id} value={item.id}>{item.modelId}</option>)}</select></label><label>主端点<select name="endpointA">{endpointOptions}</select></label><label>主端点权重<input name="weightA" type="number" min="0" max="100" defaultValue="70"/></label><label>次端点<select name="endpointB">{endpointOptions}</select></label><label>次端点权重<input name="weightB" type="number" min="0" max="100" defaultValue="30"/></label></>}{pageId === "limits" && <><label>规则名称<input name="name"/></label><label>作用层级<select name="scopeType"><option value="tenant">租户</option><option value="project">项目</option><option value="key">Key</option><option value="model">模型</option></select></label><label>作用对象 ID<input name="scopeId"/></label><label>RPM<input name="rpm" type="number" min="1" defaultValue="100"/></label><label>TPM<input name="tpm" type="number" min="1" defaultValue="100000"/></label><label>并发<input name="concurrency" type="number" min="1" defaultValue="10"/></label></>}{pageId === "fallback" && <><label>规则名称<input name="name"/></label><label>路由<select name="routeId">{state.routes.map(item => <option key={item.id} value={item.id}>{item.routeId}</option>)}</select></label><label>超时 ms<input name="timeoutMs" type="number" min="1" defaultValue="3000"/></label><label>错误率阈值 %<input name="errorRate" type="number" min="1" max="100" defaultValue="5"/></label><label>主端点<select name="primary">{endpointOptions}</select></label><label>回退端点<select name="secondary">{endpointOptions}</select></label></>}{pageId === "cache" && <><label>策略名称<input name="name"/></label><label>隔离范围<select name="scope"><option>tenant+model</option><option>project+model</option><option>key+model</option></select></label><label>TTL 秒<input name="ttl" type="number" min="1" defaultValue="600"/></label><label>排除规则<input name="exclusions" placeholder="例如敏感策略命中"/></label></>}{error && <p className="form-error">{error}</p>}<footer><button type="button" onClick={close}>取消</button><button className="v2-primary">保存草稿</button></footer></form></aside></div>;
}

function Releases({ state, dispatch }) {
  const publish = () => { const previous = state.releases.find(item => item.status === "当前生效"), number = String(state.releases.length + 1).padStart(3, "0"), next = { id: uid("release"), version: `r-${number}`, configSnapshot: `${state.routes.length} routes · ${state.limits.length} limits · ${state.fallbacks.length} fallbacks`, previousReleaseId: previous?.id || null, validation: state.routes.every(route => route.targets.reduce((sum, item) => sum + item.weight, 0) === 100) ? "通过" : "失败", diff: "发布当前草稿配置", publishedAt: new Date().toISOString(), status: "当前生效" }; if (next.validation === "失败") return; dispatch({ type: "batch", objectId: next.version, changes: [...state.releases.filter(item => item.status === "当前生效").map(item => ({ type: "update", collection: "releases", id: item.id, changes: { status: "历史版本" } })), { type: "add", collection: "releases", record: next }] }); };
  const rollback = target => { const current = state.releases.find(item => item.status === "当前生效"), next = { ...target, id: uid("release"), version: `r-${String(state.releases.length + 1).padStart(3, "0")}`, previousReleaseId: current?.id, diff: `回滚至 ${target.version}`, publishedAt: new Date().toISOString(), status: "当前生效" }; dispatch({ type: "batch", objectId: next.version, changes: [{ type: "update", collection: "releases", id: current.id, changes: { status: "历史版本" } }, { type: "add", collection: "releases", record: next }] }); };
  return <><div className="release-actions"><div><b>当前草稿</b><span>{state.routes.filter(item => item.status === "草稿").length} 条路由待发布</span></div><button className="v2-primary" onClick={publish}>校验并发布</button></div><section className="v2-list"><div className="v2-table"><table><thead><tr><th>版本</th><th>配置快照</th><th>差异</th><th>校验</th><th>状态</th><th>发布时间</th><th>操作</th></tr></thead><tbody>{state.releases.map(item => <tr key={item.id}><td>{item.version}</td><td>{item.configSnapshot}</td><td>{item.diff}</td><td><State value={item.validation}/></td><td><State value={item.status}/></td><td>{item.publishedAt.slice(0, 16).replace("T", " ")}</td><td>{item.status !== "当前生效" && <button onClick={() => rollback(item)}>回滚到此版本</button>}</td></tr>)}</tbody></table></div></section></>;
}

function Simulator({ state, dispatch }) {
  const [keyId,setKeyId]=useState("key-002"),[modelId,setModelId]=useState("model-1"),[timeout,setTimeoutFlag]=useState(false),[result,setResult]=useState("");
  const run=()=>{const requestId=`req_gateway_${Date.now()}`,planned=simulateRequest(state,{requestId,keyId,modelId,forceTimeout:timeout});dispatch({type:"batch",objectId:requestId,changes:planned.changes});setResult(`${planned.request.httpStatus} · ${planned.request.cacheHit?"缓存命中":planned.request.attempts.length>1?"回退成功":planned.request.attempts.at(-1).error||"路由成功"} · ${planned.request.releaseId||"无发布版本"}`)};
  return <section className="request-simulator"><div><b>网关请求模拟</b><span>{result||"验证鉴权、限流、选路、回退、缓存与发布版本"}</span></div><select aria-label="Key ID" value={keyId} onChange={e=>setKeyId(e.target.value)}>{state.apiKeys.map(x=><option key={x.id} value={x.id}>{x.keyId}</option>)}</select><select aria-label="Model ID" value={modelId} onChange={e=>setModelId(e.target.value)}>{state.models.map(x=><option key={x.id} value={x.id}>{x.modelId}</option>)}</select><label><input type="checkbox" checked={timeout} onChange={e=>setTimeoutFlag(e.target.checked)}/>模拟主端点超时</label><button className="v2-primary" onClick={run}>发送模拟请求</button></section>;
}

export default function GatewayPage({ pageId, state, dispatch }) {
  const [creating, setCreating] = useState(false), items = state[collection[pageId]];
  if (pageId === "releases") return <div className="v2-page"><Header pageId={pageId}/><Releases state={state} dispatch={dispatch}/></div>;
  const columns = pageId === "routes" ? ["Route ID", "名称", "Model ID", "方式", "端点 / 权重", "状态"] : pageId === "limits" ? ["规则名称", "层级 / 对象", "RPM", "TPM", "并发", "状态"] : pageId === "fallback" ? ["规则名称", "路由", "超时", "错误率", "回退链", "状态"] : ["策略名称", "隔离范围", "TTL", "排除规则", "命中率", "节省 Token", "状态"];
  const cells = item => pageId === "routes" ? [item.routeId, item.name, state.models.find(value => value.id === item.modelId)?.modelId, item.mode, item.targets.map(value => `${state.endpoints.find(ep => ep.id === value.endpointId)?.endpointId}:${value.weight}%`).join(" → "), item.status] : pageId === "limits" ? [item.name, `${item.scopeType} / ${item.scopeId}`, item.rpm, item.tpm, item.concurrency, item.status] : pageId === "fallback" ? [item.name, state.routes.find(value => value.id === item.routeId)?.routeId, `${item.timeoutMs} ms`, `${item.errorRate}%`, item.chain.map(id => state.endpoints.find(ep => ep.id === id)?.endpointId).join(" → "), item.status] : [item.name, item.scope, `${item.ttl}s`, item.exclusions, `${item.hitRate}%`, item.savedTokens.toLocaleString(), item.status];
  return <div className="v2-page"><Header pageId={pageId} onNew={() => setCreating(true)}/>{["routes","fallback","cache"].includes(pageId)&&<Simulator state={state} dispatch={dispatch}/>}<section className="v2-list"><div className="v2-table"><table><thead><tr>{columns.map(c => <th key={c}>{c}</th>)}<th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.id}>{cells(item).map((cell, i) => <td key={i}>{i === cells(item).length - 1 ? <State value={cell}/> : cell}</td>)}<td><button onClick={() => dispatch({ type: "update", collection: collection[pageId], id: item.id, changes: { status: item.status.includes("停用") ? "已启用" : "已停用" } })}>{item.status.includes("停用") ? "启用" : "停用"}</button>{pageId==="cache"&&<button onClick={()=>dispatch({type:"update",collection:"caches",id:item.id,changes:{invalidatedAt:new Date().toISOString(),hitRate:0,savedTokens:0}})}>清理缓存</button>}</td></tr>)}</tbody></table></div></section>{creating && <Editor pageId={pageId} state={state} dispatch={dispatch} close={() => setCreating(false)}/>}</div>;
}
