import { deploymentSeries, deploymentSummary } from "./observability";
import { useEffect, useMemo, useState } from "react";
import { TimeSeriesChart as SharedMetricChart } from "../components/AnalyticsCharts";
import { Activity, Boxes, CirclePlus, Cpu, Search, Server, X } from "lucide-react";

const uid = prefix => `${prefix}-${Date.now()}`;

function Modal({ title, onClose, children }) {
  useEffect(() => { const close = event => event.key === "Escape" && onClose(); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [onClose]);
  return <div className="v2-mask" onClick={onClose}><section className="inference-modal" onClick={event => event.stopPropagation()}><header><h2>{title}</h2><button aria-label="关闭" onClick={onClose}><X/></button></header>{children}</section></div>;
}

function Header({ title, description, icon: Icon, action }) {
  return <div className="v2-page-head inference-head"><div><span>Token 生产</span><h1><Icon/>{title}</h1><p>{description}</p></div>{action}</div>;
}

function State({ value }) { return <em className={`v2-status ${["维护中", "失败", "停止"].includes(value) ? "warn" : ""}`}>{value}</em>; }

export function ClusterManagement({ state, dispatch }) {
  const [query, setQuery] = useState(""), [creating, setCreating] = useState(false), [error, setError] = useState("");
  const rows = state.clusters.filter(item => `${item.name} ${item.clusterId} ${item.zone}`.toLowerCase().includes(query.toLowerCase()));
  const save = event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const totalGpu = Number(values.totalGpu); if (!values.clusterId || !values.name || totalGpu < 1) return setError("请填写唯一 Cluster ID、集群名称和正整数 GPU 数量"); if (state.clusters.some(item => item.clusterId === values.clusterId)) return setError("Cluster ID 已存在"); dispatch({ type: "add", collection: "clusters", record: { id: uid("cluster"), ...values, totalGpu, allocatedGpu: 0, nodes: Number(values.nodes), status: "运行中" } }); setCreating(false); };
  return <div className="v2-page"><Header title="集群纳管" icon={Server} description="统一纳管自有推理集群，查看节点、GPU 容量和部署占用。" action={<button className="v2-primary" onClick={() => setCreating(true)}><CirclePlus/> 纳管集群</button>}/><section className="inference-kpis"><article><Cpu/><span>GPU 总量<b>{state.clusters.reduce((sum, item) => sum + item.totalGpu, 0)}</b></span></article><article><Activity/><span>已分配<b>{state.clusters.reduce((sum, item) => sum + item.allocatedGpu, 0)}</b></span></article><article><Boxes/><span>运行集群<b>{state.clusters.filter(item => item.status === "运行中").length}</b></span></article></section><section className="v2-list"><div className="v2-toolbar"><label><Search/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索 Cluster ID、名称或可用区"/></label></div><div className="cluster-grid">{rows.map(item => { const usage = Math.round(item.allocatedGpu / item.totalGpu * 100); return <article key={item.id}><header><div><b>{item.name}</b><small>{item.clusterId}</small></div><State value={item.status}/></header><dl><span><dt>可用区</dt><dd>{item.zone}</dd></span><span><dt>GPU 型号</dt><dd>{item.gpuType}</dd></span><span><dt>节点</dt><dd>{item.nodes}</dd></span><span><dt>GPU 容量</dt><dd>{item.allocatedGpu} / {item.totalGpu}</dd></span></dl><label>资源占用 <b>{usage}%</b><i><span style={{ width: `${usage}%` }}/></i></label><footer><button onClick={() => dispatch({ type: "update", collection: "clusters", id: item.id, changes: { status: item.status === "维护中" ? "运行中" : "维护中" } })}>{item.status === "维护中" ? "恢复服务" : "进入维护"}</button><span>{state.deployments.filter(deploy => deploy.clusterId === item.id).length} 个部署</span></footer></article>; })}</div></section>{creating && <Modal title="纳管推理集群" onClose={() => setCreating(false)}><form onSubmit={save} className="inference-form"><label>Cluster ID<input name="clusterId" placeholder="例如 inference-nj-b"/></label><label>集群名称<input name="name" placeholder="请输入集群名称"/></label><label>可用区<input name="zone" defaultValue="南京"/></label><label>GPU 型号<select name="gpuType"><option>H20</option><option>L40S</option><option>A800</option></select></label><label>GPU 总量<input name="totalGpu" type="number" min="1" defaultValue="8"/></label><label>节点数量<input name="nodes" type="number" min="1" defaultValue="1"/></label>{error && <p className="form-error">{error}</p>}<footer><button type="button" onClick={() => setCreating(false)}>取消</button><button className="v2-primary">确认纳管</button></footer></form></Modal>}</div>;
}

export function ModelDeployments({ state, dispatch }) {
  const [creating, setCreating] = useState(false), [error, setError] = useState("");
  const save = event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)), replicas = Number(values.replicas), gpuPerReplica = Number(values.gpuPerReplica), cluster = state.clusters.find(item => item.id === values.clusterId), artifact = state.artifacts.find(item => item.id === values.artifactId), need = replicas * gpuPerReplica; if (!values.deploymentId || !values.name) return setError("Deployment ID 和服务名称必填"); if (state.deployments.some(item => item.deploymentId === values.deploymentId)) return setError("Deployment ID 已存在"); if (!artifact || artifact.validation !== "通过" || artifact.status !== "可运行") return setError("请选择验证通过且可运行的制品"); if (!cluster || cluster.status !== "运行中") return setError("只能部署到运行中的集群"); if (need > cluster.totalGpu - cluster.allocatedGpu) return setError(`GPU 容量不足：需要 ${need}，可用 ${cluster.totalGpu - cluster.allocatedGpu}`); dispatch({ type: "batch", objectId: values.deploymentId, changes: [{ type: "add", collection: "deployments", record: { id: uid("deployment"), ...values, replicas, gpuPerReplica, endpointId: null, status: "部署中" } }, { type: "update", collection: "clusters", id: cluster.id, changes: { allocatedGpu: cluster.allocatedGpu + need } }] }); setCreating(false); };
  const stop = item => { const cluster = state.clusters.find(value => value.id === item.clusterId), released = item.replicas * item.gpuPerReplica, changes = [{ type: "update", collection: "deployments", id: item.id, changes: { status: "停止" } }, { type: "update", collection: "clusters", id: cluster.id, changes: { allocatedGpu: Math.max(0, cluster.allocatedGpu - released) } }]; if (item.endpointId) changes.push({ type: "update", collection: "endpoints", id: item.endpointId, changes: { status: "停用" } }); dispatch({ type: "batch", objectId: item.deploymentId, changes }); };
  const resize = item => { const replicas = Number(prompt("请输入新的副本数", item.replicas)); if (!Number.isInteger(replicas) || replicas < 1 || replicas === item.replicas) return; const cluster = state.clusters.find(value => value.id === item.clusterId), delta = (replicas - item.replicas) * item.gpuPerReplica; if (delta > cluster.totalGpu - cluster.allocatedGpu) return alert("GPU 容量不足，未执行扩容"); dispatch({ type: "batch", objectId: item.deploymentId, changes: [{ type: "update", collection: "deployments", id: item.id, changes: { replicas } }, { type: "update", collection: "clusters", id: cluster.id, changes: { allocatedGpu: cluster.allocatedGpu + delta } }] }); };
  const activate = item => { const endpoint = { id: uid("endpoint"), endpointId: `ep-${item.deploymentId}`, name: item.name, providerId: "provider-self", protocol: "OpenAI", baseUrl: `https://inference.demo.invalid/${item.deploymentId}/v1`, credentialRef: "managed-by-platform", modelIds: [item.modelId], capacity: item.replicas * 3000, health: 100, status: "运行中" }; dispatch({ type: "batch", objectId: item.deploymentId, changes: [{ type: "add", collection: "endpoints", record: endpoint }, { type: "update", collection: "deployments", id: item.id, changes: { endpointId: endpoint.id, status: "运行中" } }] }); };
  return <div className="v2-page"><Header title="模型部署" icon={Boxes} description="选择模型、制品与集群完成部署，容量预检、资源占用和服务状态保持一致。" action={<button className="v2-primary" onClick={() => setCreating(true)}><CirclePlus/> 部署模型</button>}/><section className="v2-list"><div className="v2-table"><table><thead><tr><th>Deployment ID</th><th>服务名称</th><th>模型</th><th>制品</th><th>集群</th><th>副本</th><th>GPU</th><th>端点</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.deployments.map(item => <tr key={item.id}><td>{item.deploymentId}</td><td>{item.name}</td><td>{state.models.find(model => model.id === item.modelId)?.name}</td><td>{state.artifacts.find(artifact => artifact.id === item.artifactId)?.name || "—"}</td><td>{state.clusters.find(cluster => cluster.id === item.clusterId)?.name}</td><td>{item.replicas}</td><td>{item.replicas * item.gpuPerReplica}</td><td>{state.endpoints.find(endpoint => endpoint.id === item.endpointId)?.endpointId || "—"}</td><td><State value={item.status}/></td><td>{item.status === "部署中" && <button onClick={() => activate(item)}>完成部署</button>}{item.status === "运行中" && <button onClick={() => resize(item)}>扩缩容</button>}{item.status !== "停止" && <button onClick={() => stop(item)}>停止</button>}</td></tr>)}</tbody></table></div></section>{creating && <Modal title="部署模型" onClose={() => setCreating(false)}><form onSubmit={save} className="inference-form"><label>Deployment ID<input name="deploymentId" placeholder="例如 deploy-qwen-prod"/></label><label>服务名称<input name="name" placeholder="请输入服务名称"/></label><label>Model ID<select name="modelId">{state.models.map(item => <option key={item.id} value={item.id}>{item.modelId} · {item.name}</option>)}</select></label><label>运行制品<select name="artifactId">{state.artifacts.filter(item => item.validation === "通过" && item.status === "可运行").map(item => <option key={item.id} value={item.id}>{item.name} · {item.version}</option>)}</select></label><label>目标集群<select name="clusterId">{state.clusters.map(item => <option key={item.id} value={item.id}>{item.clusterId} · 可用 {item.totalGpu - item.allocatedGpu} GPU</option>)}</select></label><label>副本数<input name="replicas" type="number" min="1" defaultValue="1"/></label><label>每副本 GPU<input name="gpuPerReplica" type="number" min="1" defaultValue="1"/></label>{error && <p className="form-error">{error}</p>}<footer><button type="button" onClick={() => setCreating(false)}>取消</button><button className="v2-primary">开始部署</button></footer></form></Modal>}</div>;
}

function ObservabilityChart({ deployments, metric }) {
  const hours = Array.from({ length: 13 }, (_, index) => `${String(index * 2).padStart(2, "0")}:00`);
  return <SharedMetricChart labels={hours} series={deployments.map(item => ({ label: item.name, values: deploymentSeries(item, metric) }))} height={360} label={metric} unit={metric === "GPU 利用率" ? "%" : metric === "P95 延迟" ? "ms" : ""} />;
}

export function ModelObservability({ state }) {
  const running = state.deployments.filter(item => item.status !== "停止"), [selected, setSelected] = useState(running.map(item => item.id)), [metric, setMetric] = useState("GPU 利用率");
  const visible = useMemo(() => running.filter(item => selected.includes(item.id)), [running, selected]);
  const summary = deploymentSummary(visible);
  return <div className="v2-page"><Header title="生产观测" icon={Activity} description="按部署实例对比资源与推理性能，图表每个部署对应独立序列。"/><section className="observability-controls"><label>监控指标<select value={metric} onChange={event => setMetric(event.target.value)}><option>GPU 利用率</option><option>请求吞吐</option><option>P95 延迟</option></select></label><fieldset><legend>Deployment ID（多选）</legend>{running.map(item => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])}/>{item.deploymentId}</label>)}</fieldset></section><section className="v2-panel observability-panel"><header><div><b>{metric}趋势</b><span>近 24 小时 · {visible.length} 个部署 · 演示样本</span></div></header>{visible.length ? <ObservabilityChart deployments={visible} metric={metric}/> : <div className="v2-empty">请选择至少一个部署</div>}</section><section className="inference-kpis"><article><Activity/><span>平均 GPU 利用率<b>{summary.gpu === null ? "—" : `${summary.gpu.toFixed(1)}%`}</b></span></article><article><GaugeIcon/><span>总吞吐<b>{summary.throughput === null ? "—" : `${summary.throughput.toFixed(1)} req/s`}</b></span></article><article><Server/><span>P95 延迟<b>{summary.p95 === null ? "—" : `${summary.p95} ms`}</b></span></article></section></div>;
}

function GaugeIcon() { return <Activity/>; }
