import { useState } from "react";
import { Activity, Boxes, CirclePlus, SlidersHorizontal } from "lucide-react";

const uid = prefix => `${prefix}-${Date.now()}`;
const info = { lifecycle: ["版本与生命周期", "维护版本、验证状态、默认版本和弃用计划。", Boxes], capability: ["能力与规格", "按模型模态配置上下文、输出和推理能力。", SlidersHorizontal], validation: ["模型验证", "在兼容端点运行模拟测试并保存逐项结果。", Activity] };
function Head({ id }) { const [title, desc, Icon] = info[id]; return <div className="v2-page-head inference-head"><div><span>业务运营 / 模型中心</span><h1><Icon/>{title}</h1><p>{desc}</p></div></div>; }
function Status({ value }) { return <em className={`v2-status ${["失败", "验证失败", "已弃用"].includes(value) ? "warn" : ""}`}>{value}</em>; }

function Lifecycle({ state, dispatch }) {
  const [modelId, setModelId] = useState(state.models[0].id), [version, setVersion] = useState(""), versions = state.modelVersions.filter(item => item.modelId === modelId);
  const create = () => { if (!version || versions.some(item => item.version === version)) return; dispatch({ type: "add", collection: "modelVersions", record: { id: uid("version"), modelId, version, capabilities: state.models.find(item => item.id === modelId).capabilities, validationStatus: "未验证", isDefault: false, deprecatedAt: null, status: "草稿" } }); setVersion(""); };
  const setDefault = item => { if (item.validationStatus !== "通过") return; const changes = state.modelVersions.filter(value => value.modelId === item.modelId).map(value => ({ type: "update", collection: "modelVersions", id: value.id, changes: { isDefault: value.id === item.id, status: value.id === item.id ? "已发布" : value.status } })); changes.push({ type: "update", collection: "models", id: item.modelId, changes: { defaultVersionId: item.id } }); dispatch({ type: "batch", objectId: item.id, changes }); };
  return <><section className="model-context"><label>Model ID<select value={modelId} onChange={event => setModelId(event.target.value)}>{state.models.map(item => <option key={item.id} value={item.id}>{item.modelId}</option>)}</select></label><label>新版本<input value={version} onChange={event => setVersion(event.target.value)} placeholder="例如 v4.1"/></label><button className="v2-primary" disabled={!version} onClick={create}><CirclePlus/> 创建版本</button></section><section className="v2-list"><div className="v2-table"><table><thead><tr><th>版本</th><th>验证</th><th>默认</th><th>状态</th><th>弃用时间</th><th>操作</th></tr></thead><tbody>{versions.map(item => <tr key={item.id}><td>{item.version}</td><td><Status value={item.validationStatus}/></td><td>{item.isDefault ? "默认版本" : "—"}</td><td><Status value={item.status}/></td><td>{item.deprecatedAt || "—"}</td><td><button disabled={item.validationStatus !== "通过" || item.isDefault} onClick={() => setDefault(item)}>设为默认</button><button onClick={() => dispatch({ type: "update", collection: "modelVersions", id: item.id, changes: { deprecatedAt: "2026-12-31", status: "已弃用", isDefault: false } })}>弃用</button></td></tr>)}</tbody></table></div></section></>;
}

function Capability({ state, dispatch }) {
  const [modelId, setModelId] = useState(state.models[0].id), model = state.models.find(item => item.id === modelId), [context, setContext] = useState(model.capabilities.context), [output, setOutput] = useState(model.capabilities.output || Math.min(8192, model.capabilities.context)), [streaming, setStreaming] = useState(model.capabilities.streaming), [message, setMessage] = useState("");
  const select = id => { const item = state.models.find(value => value.id === id); setModelId(id); setContext(item.capabilities.context); setOutput(item.capabilities.output || Math.min(8192, item.capabilities.context)); setStreaming(item.capabilities.streaming); setMessage(""); };
  const save = () => { if (context < 1 || output < 1 || output > context) return setMessage("输出上限必须为正整数且不能超过上下文窗口"); dispatch({ type: "update", collection: "models", id: model.id, changes: { capabilities: { ...model.capabilities, context: Number(context), output: Number(output), streaming } } }); setMessage("能力规格已保存"); };
  return <section className="capability-layout"><aside><label>Model ID<select value={modelId} onChange={event => select(event.target.value)}>{state.models.map(item => <option key={item.id} value={item.id}>{item.modelId}</option>)}</select></label><div><small>模型类型</small><b>{model.type}</b></div><div><small>目录状态</small><Status value={model.status}/></div></aside><article><h2>基础推理能力</h2><label>上下文窗口 Tokens<input type="number" min="1" value={context} onChange={event => setContext(event.target.value)}/></label><label>最大输出 Tokens<input type="number" min="1" value={output} onChange={event => setOutput(event.target.value)}/></label>{["text", "multimodal", "audio"].includes(model.type) && <label className="switch-row"><input type="checkbox" checked={streaming} onChange={event => setStreaming(event.target.checked)}/>支持流式响应</label>}<div className="capability-preview"><b>能力预览</b><span>{model.type} · {Number(context).toLocaleString()} 上下文 · {streaming ? "流式" : "非流式"}</span></div>{message && <p className={message.includes("已保存") ? "form-success" : "form-error"}>{message}</p>}<button className="v2-primary" onClick={save}>保存规格</button></article></section>;
}

function Validation({ state, dispatch }) {
  const [versionId, setVersionId] = useState(state.modelVersions[0].id), [endpointId, setEndpointId] = useState(state.endpoints[0].id), [scenario, setScenario] = useState("成功"), [running, setRunning] = useState(false);
  const run = () => { if (running) return; const version = state.modelVersions.find(item => item.id === versionId), endpoint = state.endpoints.find(item => item.id === endpointId); if (!endpoint?.modelIds.includes(version.modelId)) return alert("该端点未映射当前模型版本，不能运行验证"); setRunning(true); const passed = scenario === "成功"; setTimeout(() => { dispatch({ type: "batch", objectId: versionId, changes: [{ type: "add", collection: "validations", record: { id: uid("validation"), modelVersionId: versionId, endpointId, cases: ["协议兼容", "流式响应", "基础推理"], passed, result: passed ? "通过" : scenario, durationMs: passed ? 860 : 3000, status: "已完成" } }, { type: "update", collection: "modelVersions", id: version.id, changes: { validationStatus: passed ? "通过" : "失败", status: passed ? "验证通过" : "验证失败" } }] }); setRunning(false); }, 450); };
  return <><section className="model-context"><label>模型版本<select value={versionId} onChange={event => setVersionId(event.target.value)}>{state.modelVersions.map(item => <option key={item.id} value={item.id}>{state.models.find(model => model.id === item.modelId)?.modelId} · {item.version}</option>)}</select></label><label>Endpoint ID<select value={endpointId} onChange={event => setEndpointId(event.target.value)}>{state.endpoints.map(item => <option key={item.id} value={item.id}>{item.endpointId}</option>)}</select></label><label>模拟结果<select value={scenario} onChange={event => setScenario(event.target.value)}><option>成功</option><option>超时</option><option>协议错误</option></select></label><button className="v2-primary" disabled={running} onClick={run}>{running ? "验证中…" : "运行验证"}</button></section><section className="validation-grid">{state.validations.map(item => <article key={item.id}><header><b>{state.modelVersions.find(value => value.id === item.modelVersionId)?.version}</b><Status value={item.result}/></header><span>{state.endpoints.find(value => value.id === item.endpointId)?.endpointId || item.endpointId}</span><ul>{item.cases.map(value => <li key={value}>{value}<em>{item.passed ? "通过" : "失败"}</em></li>)}</ul><footer>{item.durationMs} ms · {item.updatedAt.slice(0, 16).replace("T", " ")}</footer></article>)}</section></>;
}

export default function ModelPage({ pageId, state, dispatch }) { return <div className="v2-page"><Head id={pageId}/>{pageId === "lifecycle" ? <Lifecycle state={state} dispatch={dispatch}/> : pageId === "capability" ? <Capability state={state} dispatch={dispatch}/> : <Validation state={state} dispatch={dispatch}/>}</div>; }
