import { FilterReset } from "../components/FilterControls";
import { useMemo, useState } from 'react';
import { Info, RefreshCw, ArrowUp, ArrowDown } from 'lucide-react';
import { TimeSeriesChart } from '../components/AnalyticsCharts';
import SavedFilterViews from '../components/SavedFilterViews';
import { Button } from '../components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/card';
import { ToggleGroup, ToggleGroupItem } from '../components/ui/toggle-group';
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '../components/ui/tooltip';
import { overviewDemo, overviewRanking, overviewDate, compactCount } from './overview';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '../components/ui/dialog';
import './analytics.css';
const number=value=>value==null?'—':value.toLocaleString('zh-CN',{maximumFractionDigits:2});
const million=value=>(value/1e6).toLocaleString('zh-CN',{maximumFractionDigits:value && value<10000?6:3});
const percent=(value,total)=>total?`${(value/total*100).toFixed(1)}%`:'—';
const labels={self:'自营',partner:'合营',unknown:'未归类'};
function Help({label,children}) {return <Tooltip><TooltipTrigger asChild><Button className="ov-help" variant="ghost" size="icon" aria-label={`${label}说明`}><Info/></Button></TooltipTrigger><TooltipContent className="ov-tooltip" side="bottom" sideOffset={6}>{children}</TooltipContent></Tooltip>}
function Modes({label,value,onChange,items}) {return <ToggleGroup aria-label={label} type="single" variant="outline" spacing={0} value={value} onValueChange={v=>v&&onChange(v)}>{items.map(([id,text])=><ToggleGroupItem key={id} value={id}>{text}</ToggleGroupItem>)}</ToggleGroup>}
function UsageCell({period,calls}) {
  const key=calls?'calls':'total', total=period[key], before=period.previous[key], delta=before>0?(total/before-1)*100:null;
  const format=calls?value=>number(value/10000):million;
  return <td><div className="ov-number"><strong>{format(total)}</strong><span className={delta==null?'':delta>=0?'ov-up':'ov-down'}>{delta!=null&&(delta>=0?<ArrowUp/>:<ArrowDown/>)}{delta==null?'—':`${number(delta)}%`}<small>{period.comparison}</small><Help label={`${period.label}${calls?'调用次数':'Token 调用量'}环比`}>本期截至当前时刻，与上一周期相同进度比较。{overviewDate(period.previousStart)} 至 {overviewDate(period.previousEnd)}；上期为 0 时不计算环比。</Help></span></div><div className="ov-source-values">{['self','partner',...(period[calls?'unknownCalls':'unknown']?['unknown']:[])].map(source=>{const value=period[calls?source+'Calls':source];return <span key={source}><i className={`ov-dot ov-${source}`}/>{labels[source]} {format(value)} <em>({percent(value,total)})</em></span>})}</div></td>;
}
function Ranking({title,data,onSelect}) {
  const max=data[0]?.total||1;
  return <Card className="ov-rank"><CardHeader><CardTitle>{title}</CardTitle><div className="ov-legend"><span><i className="ov-dot ov-self"/>自营</span><span><i className="ov-dot ov-partner"/>合营</span></div></CardHeader><CardContent><div className="ov-rank-head"><span>排名</span><span>名称</span><span>自营 / 合营</span><span>Token 调用量</span></div>{data.length?<ol>{data.map((row,i)=><li key={row.id}><Tooltip><TooltipTrigger asChild><button type="button" className="ov-rank-row" onClick={()=>onSelect(row)}><span className={i<3?'ov-rank-top':''}>{i+1}</span><span className="ov-rank-name">{row.name}</span><span className="ov-rank-track" aria-hidden="true">{['self','partner','unknown'].map(source=><span key={source} className={`ov-${source}`} style={{width:`${row[source]/max*100}%`}}/>)}</span><strong>{million(row.total)}</strong></button></TooltipTrigger><TooltipContent className="ov-tooltip"><div><p>总量 {compactCount(row.total)} Token</p>{['self','partner','unknown'].filter(k=>row[k]>0).map(k=><p key={k} className="ov-tooltip-source"><i className={`ov-dot ov-${k}`}/>{labels[k]} {compactCount(row[k])} Token（{percent(row[k],row.total)}）</p>)}</div></TooltipContent></Tooltip></li>)}</ol>:<div className="ov-rank-empty">本期暂无 Token 调用记录</div>}</CardContent></Card>;
}
export default function OperationsOverview() {
  const [now,setNow]=useState(()=>Date.now()), [tokenDays,setTokenDays]=useState('30'), [userDays,setUserDays]=useState('30'), [rankPeriod,setRankPeriod]=useState('day');
  const [detail,setDetail]=useState(null);
  const data=useMemo(()=>overviewDemo(now),[now]), trend=data.dayTrend.slice(-Number(tokenDays)), userTrend=data.userTrend.slice(-Number(userDays)), period=data.periods.find(p=>p.id===rankPeriod);
  const total=trend.reduce((s,d)=>s+d.total,0), sources=['self','partner',...(trend.some(d=>d.unknown)?['unknown']:[])];
  const userMetrics=[['用户数',data.users.registered,'截至当前累计注册的用户数，按用户 ID 去重，包含已注销账号。'],['DAU',data.users.dau,'日活跃用户数：统计今日北京时间 00:00 至当前成功登录的用户，按用户 ID 去重；同一用户多次登录只计 1 人，不以 API 调用次数计数。'],['MAU',data.users.mau,'月活跃用户数：统计本自然月北京时间 1 日 00:00 至当前成功登录的用户，按用户 ID 在整月内去重；同一用户跨日登录只计 1 人，不是每日 DAU 之和。']];
  return <TooltipProvider><div className="an-page ov-page"><div className="an-page-actions"><div><span className="ov-updated">更新于 {new Date(now).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})} 北京时间</span><SavedFilterViews scope="admin-overview" value={{tokenDays,userDays,rankPeriod}} onApply={view=>{if(!view)return;setTokenDays(['7','30'].includes(view.tokenDays)?view.tokenDays:'30');setUserDays(['7','30'].includes(view.userDays)?view.userDays:'30');setRankPeriod(data.periods.some(period=>period.id===view.rankPeriod)?view.rankPeriod:'day')}} groups={[{label:"Token 趋势时间",text:`近 ${tokenDays} 天`,scope:"仅 Token 趋势"},{label:"用户趋势时间",text:`近 ${userDays} 天`,scope:"仅用户趋势"},{label:"排行时间",text:period.label,scope:"仅排行"}]} saveDescription="保存 Token 趋势、用户趋势和排行的时间条件，不包含顶部固定周期指标。视图仅在当前浏览器生效。"/><FilterReset onClick={()=>{setTokenDays("30");setUserDays("30");setRankPeriod("day")}}/><Button variant="outline" size="sm" onClick={()=>setNow(Date.now())}><RefreshCw/>刷新</Button></div></div>
    <Card className="ov-summary"><table className="ov-matrix" aria-label="平台用量概览"><thead><tr><th scope="col">指标</th>{data.periods.map(p=><th scope="col" key={p.id}>{p.label}{p.range&&`（${p.range}）`}</th>)}</tr></thead><tbody>{[false,true].map(calls=><tr key={String(calls)}><th scope="row"><div>{calls?'模型调用次数':'Token 调用量'}<Help label={calls?'模型调用次数':'Token 调用量'}>{calls?'统计平台请求次数，包含成功与失败请求。':'输入 + 输出 Token；缓存不重复计数，不混合图片、秒数等计量单位。'}按服务供给来源区分自营与合营，无法归属的请求单列为未归类。</Help></div><small>{calls?'万次':'百万 Token'}</small></th>{data.periods.map(p=><UsageCell key={p.id} period={p} calls={calls}/>)}</tr>)}</tbody></table>
      <div className="ov-metrics-scroll"><div className="ov-metrics">{userMetrics.map(([label,value,note])=><div key={label}><span>{label}<Help label={label}>{note}</Help></span><strong>{number(value)}</strong></div>)}<div><span>今日调用成功率<Help label="今日调用成功率">今日 2xx 请求数 / 总请求数；无请求时显示 —。</Help></span><strong>{data.success==null?'—':`${number(data.success)}%`}</strong></div>{[['response','响应时延','请求发出至收到完整响应的耗时。'],['ttft','TTFT','首 Token 时延：请求发出至收到首个 Token 的耗时。'],['tpot','TPOT','单个请求从首个到最后一个输出 Token 的耗时，除以输出 Token 数减 1；输出不足 2 个 Token 的请求不参与统计。']].map(([key,title,note])=><div key={key}><span>{title}<Help label={title}>{note}平均值为今日有效请求样本的算术平均值，最大值为其中最高值；当前有效样本 {data[key].count} 个，无数据或不适用时显示 —。</Help></span><div className="ov-latency"><span>平均 <strong>{number(data[key].avg)}</strong><small>ms</small></span><span className="ov-max">最大 {number(data[key].max)} ms</span></div></div>)}</div></div>
      <p className="ov-footnote">全部为模拟数据 · 环比对比上一周期同期进度 · 质量指标统计今日</p>
    </Card>
    <div className="ov-two-columns"><Card><CardHeader><CardTitle>Token 调用量趋势</CardTitle><Modes label="Token 趋势时间" value={tokenDays} onChange={setTokenDays} items={[["7","近 7 天"],["30","近 30 天"]]}/></CardHeader><CardContent><p className="ov-chart-summary">区间累计 <b>{million(total)}</b> 百万 · 日均 <b>{million(total/trend.length)}</b> 百万<Help label="Token 趋势时间">按北京时间逐日汇总，今日统计至当前时刻。区间累计为所选日期的 Token 总量，日均为区间累计除以所选天数；无调用的日期计为 0。</Help></p><TimeSeriesChart labels={trend.map(d=>d.label)} series={sources.map(k=>({label:`${labels[k]} Token`,color:k==='unknown'?'#8893a3':undefined,values:trend.map(d=>d[k]/1e6)}))} unit="百万 Token" label="Token 调用量趋势" height={230}/></CardContent></Card>
      <Card><CardHeader><CardTitle>用户趋势</CardTitle><Modes label="用户趋势时间" value={userDays} onChange={setUserDays} items={[["7","近 7 天"],["30","近 30 天"]]}/></CardHeader><CardContent><p className="ov-chart-summary">近 {userDays} 天 · 按日去重 · 人</p><TimeSeriesChart labels={userTrend.map(d=>d.label)} series={[{label:'新增注册',values:userTrend.map(d=>d.registered)},{label:'登录活跃',values:userTrend.map(d=>d.active)},{label:'注销',color:'#8893a3',values:userTrend.map(d=>d.cancelled)}]} unit="人" label="用户趋势" height={230}/></CardContent></Card></div>
    <div className="ov-ranking-heading"><div><h2>Token 调用排行</h2><Help label="排行统计对象">按所选时间范围内的 Token 调用总量降序展示前 10 名用户和模型，包含输入与输出 Token；色条分别表示自营与合营用量。</Help></div><div><Modes label="排行时间" value={rankPeriod} onChange={setRankPeriod} items={data.periods.map(p=>[p.id,p.label])}/><small>单位：百万 Token</small></div></div>
    <div className="ov-two-columns"><Ranking title={period.label+" Token 用量 Top10 用户"} data={overviewRanking(period,'user')} onSelect={setDetail}/><Ranking title={period.label+" Token 调用 Top 10 模型"} data={overviewRanking(period,'model')} onSelect={setDetail}/></div>
    <Dialog open={Boolean(detail)} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent><DialogHeader><DialogTitle>{detail?.name} · 模拟用量</DialogTitle><DialogDescription>{period.label} · {overviewDate(period.start)} — {overviewDate(period.end)} · 模拟数据</DialogDescription></DialogHeader>{detail&&<dl className="grid grid-cols-2 gap-3"><dt>Token 调用量</dt><dd>{million(detail.total)} 百万</dd><dt>自营</dt><dd>{million(detail.self)} 百万（{percent(detail.self,detail.total)}）</dd><dt>合营</dt><dd>{million(detail.partner)} 百万（{percent(detail.partner,detail.total)}）</dd><dt>模型调用次数</dt><dd>{number(detail.calls)} 次</dd><dt>占平台 Token 用量</dt><dd>{percent(detail.total,period.total)}</dd></dl>}</DialogContent></Dialog>
  </div></TooltipProvider>;
}
