// Run with playwright-cli run-code using this file's contents, after opening the local app.
async (page) => {
  await page.reload();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const check = (value, message) => { if (!value) throw new Error(message); };
  const checkModelPlacement = async () => { const model = await page.locator('.pg-model').boundingBox(); const send = await page.locator('.pg-send').boundingBox(); check(model && send && model.x < send.x && send.x - model.x - model.width < 8 && Math.abs(model.y - send.y) < 2, 'Model picker must sit immediately left of send'); };
  const checkPromptsAboveComposer = async () => { const prompts = await page.locator('.pg-prompts').boundingBox(); const composer = await page.locator('.pg-composer').boundingBox(); check(prompts && composer && prompts.y + prompts.height < composer.y, 'Prompt chips must sit above composer'); };
  await page.getByRole('button', { name: '文本生成', exact: true }).click();
  check((await page.locator('aside h3').innerText()) === '模型服务平台', 'Sidebar uses the platform name');
  check(await page.locator('aside').getByRole('button', { name: '多模态模型', exact: true }).count() === 0, 'Multimodal is merged into text generation');
  check((await page.locator('aside').innerText()).includes('用量分析'), 'Usage navigation is named analysis');
  check(await page.locator('aside').getByRole('button', { name: '模型对比', exact: true }).count() === 0, 'Comparison is not a standalone sidebar entry');
  check((await page.locator('.pg-heading p').innerText()).includes('多模态模型还可以理解图片、视频'), 'Text generation explains merged multimodal capabilities');
  check(await page.getByRole('button', { name: '联网搜索', exact: true }).count() === 0, 'Web search is hidden');
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  check((await page.getByRole('status').innerText()).includes('已创建新对话'), 'Empty-state new conversation gives feedback');
  check(await page.getByRole('button', { name: '发送', exact: true }).isDisabled(), 'Empty input must not send');
  check(await page.locator('.pg-composer .pg-model-picker').count() === 1, 'Model picker belongs in composer');
  check((await page.getByLabel('选择模型').innerText()).includes('DeepSeek/DeepSeek-V4-Pro'), 'Model trigger uses provider/model ID');
  check(await page.getByLabel('选择模型').locator('img').count() === 0, 'Model trigger does not show a logo');
  check((await page.locator('.pg-quota-note').innerText()).includes('已订购的模型额度'), 'Composer explains quota consumption');
  await checkModelPlacement();
  await page.getByLabel('选择模型').click();
  check(await page.getByRole('menu', { name: '模型列表' }).isVisible(), 'Model picker opens a structured list');
  check(await page.getByRole('menuitem').count() === 6, 'Text generation lists text and multimodal models together');
  check(await page.getByRole('menuitem', { name: /DeepSeek-V4-Pro.*已订购.*Token Plan/ }).isVisible(), 'Subscribed Token Plan model is identified');
  check(await page.getByRole('menuitem', { name: /Qwen3.7-Max.*未订购.*按量计费/ }).isVisible(), 'Unsubscribed metered model is identified');
  await page.getByRole('menuitem', { name: /GLM-5.2/ }).click();
  check(await page.locator('.pg-prompts button svg.lucide-arrow-down-right').count() === 3, 'Text suggestions use unified prompt chips');
  await checkPromptsAboveComposer();
  await page.getByRole('button', { name: '项目总结报告', exact: true }).click();
  check((await page.getByLabel('体验输入').inputValue()).length > 80, 'Text preset inserts a detailed prompt');
  await page.getByRole('button', { name: '开启深度思考', exact: true }).click();
  check(await page.getByRole('button', { name: '关闭深度思考', exact: true }).getAttribute('aria-pressed') === 'true', 'Deep thinking icon toggles in composer');
  await page.getByLabel('参数设置').click();
  const modelSettings = page.getByRole('dialog', { name: '模型设置' });
  check(await modelSettings.isVisible(), 'Text model settings opens as a dialog');
  check((await modelSettings.locator('header').innerText()).includes('GLM-5.2 模型设置'), 'Settings title follows selected model');
  await page.getByLabel('System Prompt').fill('你是一个严谨的企业 AI 助手。');
  check(await page.getByRole('slider', { name: 'Temperature' }).isVisible(), 'Temperature must open');
  check(await page.getByRole('slider', { name: 'Top P' }).isVisible(), 'Top P must open');
  check(await page.getByRole('slider', { name: 'Thinking Budget' }).isVisible(), 'Thinking budget must open');
  await page.getByLabel('添加停止词').click();
  await page.getByRole('textbox', { name: '停止词' }).fill('<END>');
  await page.getByRole('slider', { name: 'Temperature' }).fill('1.2');
  await page.getByRole('slider', { name: 'Top P' }).fill('0.75');
  await page.getByRole('slider', { name: 'Thinking Budget' }).fill('6000');
  await modelSettings.getByRole('button', { name: '保存', exact: true }).click();
  check((await page.getByRole('status').innerText()).includes('模型参数已保存'), 'Settings save gives feedback');
  await page.getByLabel('参数设置').click();
  await page.getByRole('slider', { name: 'Temperature' }).fill('1.3');
  await modelSettings.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  check(await page.getByRole('dialog').isVisible(), 'Draft requires confirmation before clearing');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  check((await page.getByLabel('体验输入').inputValue()).length > 0, 'Cancel preserves draft');
  await page.getByLabel('体验输入').press('Enter');
  await page.locator('.pg-answer').waitFor();
  check(await page.getByRole('heading', { name: '建议从以下三个方面着手' }).isVisible(), 'Text response uses structured readable content');
  check(await page.getByRole('button', { name: '复制 MD', exact: true }).isVisible(), 'Response exposes Markdown copy action');
  await page.getByRole('button', { name: '有帮助', exact: true }).click();
  check(await page.getByRole('button', { name: '有帮助', exact: true }).getAttribute('aria-pressed') === 'true', 'Response feedback toggles');
  const composerBox = await page.locator('.pg-composer').boundingBox();
  check(composerBox && Math.abs((composerBox.y + composerBox.height) - page.viewportSize().height) < 70, 'Composer must move to viewport bottom after first response');
  await page.getByLabel('参数设置').click();
  check(await modelSettings.isVisible(), 'Model settings remains accessible in conversation state');
  await modelSettings.getByLabel('关闭模型设置').click();
  check((await page.locator('.pg-answer').innerText()).includes('GLM-5.2'), 'Response preserves model');
  check((await page.locator('.pg-answer').innerText()).includes('temperature 1.2 · top_p 0.75'), 'Response reflects sampling parameters');
  check((await page.locator('.pg-answer').innerText()).includes('深度思考'), 'Response reflects deep-thinking state');
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await page.getByRole('button', { name: '确认新建', exact: true }).click();
  check(await page.locator('.pg-answer').count() === 0, 'New conversation clears result');
  await page.getByRole('button', { name: '模型对比', exact: true }).click();
  check(await page.locator('.compare-column').count() === 2, 'Comparison starts with two text models');
  check(await page.locator('button[title="联网搜索"]').count() === 0, 'Web search is hidden in comparison mode');
  await page.locator('.compare-composer textarea').first().fill('比较模型回答');
  check((await page.locator('.compare-composer textarea').nth(1).inputValue()) === '比较模型回答', 'Synchronized input mirrors across columns');
  await page.locator('.compare-send').first().click();
  await page.getByText('2 个模型已完成对比', { exact: true }).waitFor();
  check(await page.locator('.compare-response').count() === 2, 'Synchronized send completes both models');
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  check(await page.getByRole('menu', { name: '选择对比模型' }).isVisible(), 'Add model opens the selection panel');
  check(await page.getByRole('menuitemcheckbox', { name: /DeepSeek-V4-Pro.*已订购.*Token Plan/ }).isVisible(), 'Comparison picker shows subscription and Token Plan status');
  check(await page.getByRole('menuitemcheckbox', { name: /Qwen3.7-Max.*未订购.*按量计费/ }).isVisible(), 'Comparison picker shows unsubscribed metered status');
  await page.getByRole('menuitemcheckbox', { name: /DeepSeek-V4-Flash/ }).click();
  check(await page.locator('.compare-column').count() === 3, 'Comparison supports a third model');
  await page.locator('.compare-head-actions label').click();
  check(!(await page.getByLabel('同步输入').isChecked()), 'Synchronized input can be disabled');
  await page.locator('.compare-composer textarea').nth(2).fill('只测试第三个模型');
  check((await page.locator('.compare-composer textarea').first().inputValue()) === '', 'Independent input stays isolated');
  await page.locator('.compare-send').nth(2).click();
  await page.getByText('DeepSeek/DeepSeek-V4-Flash 已完成生成', { exact: true }).waitFor();
  check(await page.locator('.compare-response').count() === 3, 'Independent send updates only its column');
  await page.locator('button[title="参数设置"]').first().click();
  check(await page.getByLabel('第 1 栏 Temperature').isVisible() && await page.getByLabel('第 1 栏 Top P').isVisible(), 'Each comparison column has independent parameters');
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  await page.getByRole('menuitemcheckbox', { name: /DeepSeek-V4-Flash/ }).click();
  check(await page.locator('.compare-column').count() === 2, 'Selected models can be removed from the picker');
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  await page.getByRole('menuitemcheckbox', { name: /Qwen3.7-Max/ }).click();
  check((await page.locator('.compare-notice').innerText()).includes('尚未订购'), 'Unsubscribed models explain why they cannot be added');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '返回单模型', exact: true }).click();
  check(await page.getByRole('heading', { name: '文本生成', exact: true }).isVisible(), 'Comparison returns to text generation');
  await checkModelPlacement();
  const multiSettings = await page.getByLabel('参数设置').boundingBox(); const multiAdd = await page.getByRole('button', { name: '添加图片或视频', exact: true }).boundingBox();
  check(multiSettings && multiAdd && multiSettings.x < multiAdd.x, 'Parameter icon precedes upload icon');
  check(await page.getByRole('button', { name: '添加图片或视频', exact: true }).locator('svg.lucide-circle-plus').isVisible(), 'Multimodal attachment entry uses CirclePlus');
  check(await page.getByLabel('参数设置').locator('svg.lucide-sliders-horizontal').isVisible(), 'Parameter entry uses SlidersHorizontal');
  check((await page.locator('.pg-heading p').innerText()).includes('多模态模型还可以理解图片、视频'), 'Header contains the merged multimodal definition');
  check(await page.locator('.pg-prompts button svg.lucide-arrow-down-right').count() === 3, 'Multimodal suggestions use unified prompt chips');
  await checkPromptsAboveComposer();
  await page.getByLabel('选择模型').click();
  await page.getByRole('menuitem', { name: /GLM-4.6V.*未订购.*按量计费.*去订购/ }).click();
  check(await page.getByRole('heading', { name: '订购模型管理' }).isVisible(), 'Unsubscribed model opens ordering page');
  await page.getByRole('button', { name: '文本生成', exact: true }).click();
  await page.getByLabel('体验输入').fill('分析图片');
  await page.getByLabel('体验输入').press('Enter');
  await page.locator('.pg-answer').waitFor();
  check((await page.locator('.pg-question').innerText()).includes('分析图片'), 'Multimodal composer accepts text-only input');
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await page.getByRole('button', { name: '确认新建', exact: true }).click();
  await page.locator('input[type=file]').evaluate(input => { const data = new DataTransfer(); data.items.add(new File(['invalid'], 'invalid.txt', { type: 'text/plain' })); input.files = data.files; input.dispatchEvent(new Event('change', { bubbles: true })); });
  check((await page.locator('.pg-feedback').innerText()).includes('图片或视频'), 'Reject invalid file type');
  await page.locator('input[type=file]').setInputFiles('public/assets/model-1.jpg');
  await page.getByAltText('待分析图片预览').waitFor();
  await page.screenshot({ path: 'output/playwright/experience-multi-after.png' });
  await page.getByRole('button', { name: '发送', exact: true }).click();
  await page.locator('.pg-answer').waitFor();
  check((await page.locator('.pg-question').innerText()).includes('请分析这个文件'), 'Multimodal composer accepts attachment-only input');
  await page.getByRole('button', { name: '图片生成', exact: true }).click();
  await checkModelPlacement();
  await checkPromptsAboveComposer();
  await page.getByLabel('参数设置').click();
  check(await page.getByLabel('图片尺寸').isVisible() && await page.getByLabel('生成数量').isVisible() && await page.getByLabel('智能改写').isVisible(), 'Image generation exposes interface parameters');
  await page.getByLabel('生成数量').selectOption('2');
  await page.getByLabel('参数设置').click();
  await page.getByRole('button', { name: '未来城市夜景', exact: true }).click();
  check((await page.getByLabel('体验输入').inputValue()).length > 80, 'Image preset inserts a detailed prompt');
  await page.getByRole('button', { name: '生成图片', exact: true }).click();
  await page.getByAltText('生成图片 2').waitFor();
  check(await page.locator('.pg-generation-result img').count() === 2, 'Image result follows selected count');
  await page.getByRole('button', { name: '视频生成', exact: true }).click();
  await checkModelPlacement();
  await page.getByLabel('参数设置').click();
  const videoSettings = page.locator('.pg-settings-panel');
  check(await videoSettings.getByLabel('生成模式').isVisible() && await videoSettings.getByLabel('视频分辨率').isVisible() && await videoSettings.getByLabel('视频比例').isVisible() && await videoSettings.getByLabel('视频时长').isVisible() && await videoSettings.getByLabel('生成声音').isVisible(), 'Video generation exposes interface parameters');
  await videoSettings.getByLabel('视频时长').selectOption('10秒');
  await videoSettings.getByLabel('生成声音').uncheck();
  await page.getByLabel('参数设置').click();
  await page.getByRole('button', { name: '云海日出航拍', exact: true }).click();
  check((await page.getByLabel('体验输入').inputValue()).length > 80, 'Video preset inserts a detailed prompt');
  await page.getByRole('button', { name: '生成视频', exact: true }).click();
  await page.getByRole('button', { name: '播放视频预览' }).waitFor();
  await page.getByRole('button', { name: '播放视频预览' }).click();
  check(await page.getByRole('button', { name: '暂停视频预览' }).isVisible(), 'Video preview toggles');
  await page.getByRole('button', { name: '语音生成', exact: true }).click();
  await checkModelPlacement();
  check(await page.locator('.pg-answer').count() === 0, 'Modes must not leak messages');
  check(await page.getByRole('button', { name: '添加音频', exact: true }).locator('svg.lucide-circle-plus').isVisible(), 'ASR attachment entry matches multimodal icon interaction');
  const asrSettings = await page.getByLabel('参数设置').boundingBox(); const asrAdd = await page.getByRole('button', { name: '添加音频', exact: true }).boundingBox();
  check(asrSettings && asrAdd && asrSettings.x < asrAdd.x, 'ASR tool order matches multimodal composer');
  check((await page.locator('.pg-tabs button[aria-pressed=true]').innerText()).includes('语音识别'), 'Voice mode uses a segmented active state');
  const voiceTabs = await page.locator('.pg-tabs').boundingBox(); const voiceComposer = await page.locator('.pg-composer').boundingBox();
  check(voiceTabs && voiceComposer && Math.abs(voiceTabs.x + voiceTabs.width / 2 - voiceComposer.x - voiceComposer.width / 2) < 2, 'Voice mode selector is centered above the experience');
  await page.getByLabel('参数设置').click();
  check(await page.getByLabel('识别语种').isVisible(), 'SenseVoice exposes language_hints');
  await page.getByLabel('识别语种').selectOption('zh');
  await page.getByLabel('过滤语气词').check();
  check(await page.getByLabel('过滤语气词').isChecked(), 'SenseVoice exposes disfluency removal');
  await page.getByLabel('参数设置').click();
  await page.locator('input[type=file]').evaluate(input => { const data = new DataTransfer(); data.items.add(new File([new Uint8Array(44)], 'sample.wav', { type: 'audio/wav' })); input.files = data.files; input.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.getByRole('button', { name: '开始转写', exact: true }).click();
  await page.locator('.pg-answer').waitFor();
  await page.screenshot({ path: 'output/playwright/experience-asr-after.png' });
  await page.getByRole('button', { name: '语音合成', exact: true }).click();
  check(await page.locator('.pg-tts-model').isVisible(), 'TTS model picker sits above the composer');
  check((await page.getByLabel('选择模型').innerText()).includes('CosyVoice'), 'TTS model must match mode');
  check(await page.getByRole('heading', { name: '音色库' }).isVisible(), 'TTS landing includes a voice library');
  check(await page.locator('.pg-voice-library>div>button').count() === 8, 'TTS voice library shows eight choices');
  await page.getByLabel('参数设置').click();
  check(await page.getByLabel('发音人').isVisible(), 'CosyVoice exposes voice');
  check(await page.getByLabel('输出格式').isVisible(), 'CosyVoice exposes format');
  check(await page.getByRole('slider', { name: '音调' }).isVisible(), 'CosyVoice exposes pitch');
  check(await page.getByRole('slider', { name: '音量' }).isVisible(), 'CosyVoice exposes volume');
  await page.getByLabel('参数设置').click();
  await page.getByLabel('体验输入').fill('你好，这是语音试听。');
  await page.getByRole('button', { name: '生成语音', exact: true }).click();
  await page.getByRole('button', { name: '试听（浏览器语音）', exact: true }).waitFor();
  await page.screenshot({ path: 'output/playwright/experience-tts-after.png' });
  await page.getByRole('button', { name: '文本生成', exact: true }).click();
  await page.setViewportSize({ width: 768, height: 900 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Tablet overflow');
  await page.screenshot({ path: 'output/playwright/experience-tablet.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Narrow Web overflow');
  await page.getByLabel('选择模型').click();
  const narrowMenu = await page.getByRole('menu', { name: '模型列表' }).boundingBox();
  check(narrowMenu && narrowMenu.x >= 0 && narrowMenu.x + narrowMenu.width <= 390, 'Model menu stays inside narrow Web viewport');
  await page.keyboard.press('Escape');
  check(!(await page.getByRole('menu', { name: '模型列表' }).isVisible()), 'Escape closes model menu');
  await page.getByLabel('参数设置').click();
  const narrowSettings = await page.getByRole('dialog', { name: '模型设置' }).boundingBox();
  check(narrowSettings && narrowSettings.x >= 0 && narrowSettings.x + narrowSettings.width <= 390, 'Model settings stays inside narrow Web viewport');
  await page.getByRole('dialog', { name: '模型设置' }).getByLabel('关闭模型设置').click();
  await page.getByRole('button', { name: '模型对比', exact: true }).click();
  await page.getByRole('button', { name: '添加模型', exact: true }).click();
  const narrowCompareMenu = await page.getByRole('menu', { name: '选择对比模型' }).boundingBox();
  check(narrowCompareMenu && narrowCompareMenu.x >= 0 && narrowCompareMenu.x + narrowCompareMenu.width <= 390, 'Comparison model picker stays inside narrow Web viewport');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Comparison page avoids document overflow');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '返回单模型', exact: true }).click();
  await page.screenshot({ path: 'output/playwright/experience-narrow.png' });
  await page.setViewportSize({ width: 1487, height: 1058 });
  await page.screenshot({ path: 'output/playwright/experience-text-after.png' });
  check(errors.length === 0, errors.join('\n'));
  console.log('PASS: structured answer actions, model selection, parameters, send, reset, upload validation and preview, ASR/TTS states, navigation isolation, responsive overflow; no page errors. Audio audibility is not verified.');
}
